designmynight/laravel-elasticsearch

src/DesignMyNight/Elasticsearch/QueryGrammar.php

So the filter aggregation can be created by calling `$builder->where()` or `$builder->filterWhere()` with the same effect.
FYI @DMNSteve @alasdairmackenzie

fix: include filters and query wheres in the filter

---

src/DesignMyNight/Elasticsearch/EloquentBuilder.php
src/DesignMyNight/Elasticsearch/QueryGrammar.php
src/DesignMyNight/Elasticsearch/QueryProcessor.php

I removed some `else` statements which followed `return` statements in `if` blocks. The `else` statements are redundant due to the `return` statements so can be removed reduce indentation and make the code easier to read.

refactor: Remove else statements after return

---

src/DesignMyNight/Elasticsearch/QueryBuilder.php
src/DesignMyNight/Elasticsearch/QueryGrammar.php

An 'exists' clause has a [different meaning in SQL](http://dev.mysql.com/doc/refman/4.1/en/exists-and-not-exists-subqueries.html), so rather than reusing the Eloquent `whereExists` method we should treat 'exists' as an operator.

refactor: treat 'exists' as an operator rather than using exists method

---

src/DesignMyNight/Elasticsearch/EloquentBuilder.php
src/DesignMyNight/Elasticsearch/QueryBuilder.php

As we talked about on Friday.
I added a new method to the `EloquentBuilder` class because I thought there'd be a couple of advantages to this approach:
* It's backwards compatible for existing code which is expecting aggregations to be returned as an array
* The method can be used similar to the `get()` method for retrieving results.
Although, on the second point, my use case is that I'm only interested in the aggregation results and not the hits. So possibly this approach doesn't work for all use cases 🤔

feat: Added support for getting aggregation results as a custom collection

---

src/DesignMyNight/Elasticsearch/EloquentBuilder.php

I tried to use the setModel() function but the type isn't used in the ES query. It looks like the `type` method is used for inserts, updates, and deletes but the `whereType` method is used for selects.

fix: querying by model type

---

src/DesignMyNight/Elasticsearch/Searchable.php

I added some methods to my Model class which I thought might be useful as part of the `Searchable` trait.
`newElasticsearchQuery()` is similar to Eloquent's `newQuery(). Together with `getElasticsearchConnectionName()` it allows client code to avoid having the ES connection name duplicated whenever an ES query is made.
`newElasticsearchQuery()` also ensures that only models of the same type are returned.

Query helper

---

src/DesignMyNight/Elasticsearch/Connection.php

@alasdairmackenzie I've made a similar change to this in core (designmynight/dmn#23596), adding the ability to set a connection timeout so we don't get Apache processes tied up waiting for Elasticsearch if it's unresponsive.
I've left this with no default, but consumers could do this to set it
`$query->getConnection()->setRequestTimeout(5);`
There are other client params you can pass to Elasticsearch (eg connection_timeout) that I haven't included here, but that I've assumed will be added in future with my generic naming of `addClientParams()`

feat: add option for request timeout

---

src/DesignMyNight/Elasticsearch/QueryGrammar.php

Fixes #21.
Usage:
```php
->aggregation(
'date',
'date_histogram',
[
'field' => 'date',
'interval' => 'day',
'min_doc_count' => 0,
'extended_bounds' => [
$dateFrom, // an instance of DateTime is allowed
$dateTo
]
]
)
```

fix: #21, can now specify min_doc_count and extended_bounds

---

src/QueryGrammar.php

@willtj Made a change so that any field can have a boost applied to it

fix: closes #34 by determining the clause term key instead of using type

---

src/QueryBuilder.php
src/QueryGrammar.php

@willtj I've added the ability to function score.  https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html
For example:
```php
$this->queryBuilder->functionScore('field_value_factor',[
'factor' =>  1,
'missing' => 1,
'field' => 'object.page_options.search_boost',
'modifier' => 'log'
]);
```
I went through a number of iterations on this, originally using only allowing `field_value_factor`.  I wanted to make this flexible to save having to implement each type of function score.  That makes the code a little more elastic search specific.  
Not sure how else would be best to approach without inlining the ES specific params.
Thoughts?

feat: add ability to apply function scores

---

src/Aggregation.php
src/QueryBuilder.php

This expands my previous PR which added the ability to pass an objedct as the last parameter of the aggregation method.
With this PR an object can be the only argument to `aggregation()` so that an aggregation object can include the key, type, and arguments for the aggregation as well as building the aggregation.
Slack me when you read this and I'll send you a link showing this PR being used as an example of the use case.

Add support for a single object argument to QueryBuilder::aggregation()

---

src/Connection.php

This updates the query execution methods to use the `run` method provided by `Illuminate\Database\Connection` (https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Database/Connection.php#L614)
This ensures that events are fired when queries are executed, making it possibly to easily get the execution time of a query:
```
DB::listen(function($query) {
// $query->sql
// $query->bindings
// $query->time
});
```
For logging purposes this still isn't entirely useful as the query SQL will contain any bindings. It might be helpful to look whether we could extend the base connection class in some way so that, although Elasticsearch doesn't use bind parameters, they would still be used within this library for comparing queries with different …

fix: query events not fired by calling BaseConnection::run()

---

src/QueryGrammar.php

I'm trying to use the `extended_bounds` parameter for the data histogram aggregation which was added in https://github.com/designmynight/laravel-elasticsearch/pull/22.
Because I'm stupid my mappings specified a different date format to the one being used at https://github.com/designmynight/laravel-elasticsearch/blob/30974149a8cfda92f1e161b0c10abbc8a679d587/src/DesignMyNight/Elasticsearch/QueryGrammar.php#L1018
I've got a method which I already use to pass an array of dates in the correct format. But this isn't working at the moment because `->format()` is being called on a string.
I'm not sure that this check belongs in the `convertDateTime` method but it seemed tidier than changing the `compileDateHistogramAggregation` method. Also, as there's no typehint on the `convertDateTime` it's …

fix: if argument to convertDateTime is a string then don't attempt to format it

---

.editorconfig
src/Console/Mappings/AliasMakeCommand.php
src/Console/Mappings/IndexListCommand.php
src/Console/Mappings/MappingMigrateCommand.php
src/Console/Mappings/Traits/GetsIndices.php
src/Console/Mappings/Traits/UpdatesAlias.php
tests/Console/Mappings/MappingMigrateCommandTest.php

@willtj 
This is an update to automatically add index aliasing for migration
When creating an index through migrations the package currently creates the index named with the timestamp of the migration.  I.e. `2018_08_02_162200_indexname`
For a friendlier way of of referring to the index one can use an alias.  In fact migration already supports automatically swapping the alias during an 'update' migration.
This PR allows you to create an alias with `php artisan make:mapping-alias`
But also, when you run the migration it will assume you want an alias and not use that timestamp. So when you migrate it will create the alias `indexname` for `2018_08_02_162200_indexname`
Also covered that if you are running migrations for the first time it will ensure the alias points to the last (most up to …

feat: index migration aliases

---

src/Connection.php
src/QueryException.php

Because the ES query is an array so can't neatly be included  in the exception message like an SQL query could.

fix: don't try to include the query/bindings

---

src/ElasticsearchServiceProvider.php

Default DatabaseManager disconnect() method tries to disconnect connections by name and no name was defaulting to the default connection being disconnected when an ES query was executed.

fix: set name of connection

---

src/Console/Mappings/Traits/UpdatesAlias.php

"update" wasn't being removed from index name when getting the alias name.

fix: remove update when getting alias name

---

src/Searchable.php

@JasparGupta this fixes an issue where the model's connection was being left as Elasticsearch if the ES operation threw an exception

fix: still put the connection back if ES failed

---

src/Connection.php

FYI @willtj 
```
Declaration of DesignMyNight\Elasticsearch\Connection::rollBack() must be compatible with Illuminate\Database\Connection::rollBack($toLevel = NULL)  
```

fix: declaration of Client::rollback()

---

src/EloquentBuilder.php
src/QueryGrammar.php

So I've had a mammoth of a hard time with date formats involving hydrating models using the correct format. 
This should help solve the issue I've had where Carbon/Laravel has been trying to automatically parse dates behind the scenes where I need the date format to be `Y-m-d\TH:i:s` coming from Elasticsearch as thats how they're stored by default. But I also need the date format to be `Y-m-d H:i:s` when being returned from MongoDB.
However when calling `::hydrate()` without passing the connection, it defaults to Mongo, and throws a hissy fit.

refactor: pass connection when hydrating a model

---

src/EloquentBuilder.php
src/QueryBuilder.php
src/QueryGrammar.php
src/Searchable.php

@robbytaylor can I get your review on this please? This is to merge into the 2.1 branch and then I'll also merge to master for a 3.0 release.
The `hydrate()` change and related date format stuff is a fix being copied over from the 3.0 branch.
The main change adds a `setKeysForSearch()` method to the Searchable trait, overridable by individual models, that will add extra query parameters to be used when searching for a document, and follows a similar approach to Laravel's Model method `setKeysForSaveQuery()`. In the Collins API codebase this will allow us to carry out actions on embedded models directly - currently doing `$deposit->delete()` throws an Elasticsearch routing exception because the deposit type is a child of a booking in Elasticsearch, and ES wants the booking ID to be passed …

2.1 fix deleting child documents

---

src/QueryBuilder.php

Otherwise date defaults to start of epoch, so we get lots of results for DOBs in January when customers just have no DOB set.

fix: require field to exist

---

src/Searchable.php

I've had an issue that was hard to debug. Eventually I figured out that the problem was due to updating a searchable model after it had been saved.
The save was changing the connection name to `elasticsearch`. The subsequent update was then running against the ElasticSearch query builder rather than the MongoDB query builder.
This should have been handled by the existing code, but it isn't. I think Laravel is being clever somewhere, I'm not sure where, and keeping the previous query builder. So changing the connection name back doesn't change the query builder instance which is used on the subsequent query.
This approach creates a copy of the model and runs the elasticsearch query on the clone, ensuring the original model retains it's initial state.

fix: perform ES queries on cloned model

---

src/Collection.php

Changes in https://github.com/designmynight/laravel-elasticsearch/pull/74 assume that the instance is going to be the first argument.

fix: only pass instance

---

src/Console/Mappings/CopyIndexCommand.php
src/Console/Mappings/IndexCopyCommand.php
src/ElasticsearchServiceProvider.php

Uses an Elasticsearch scroll cursor to re-index all documents from one index to a new index - useful if you have updated a mapping and can reindex from existing ES data rather than having to reindex from the database.

feat: command to copy all documents to a new index

---

src/Connection.php
src/Console/Mappings/IndexCopyCommand.php

The cursor method was defaulting to 100,000 records and failing to allow it to be set to zero, so copying the index was stopping after hitting that limit.

Fix copy index command

---

src/QueryBuilder.php
src/QueryGrammar.php

I needed to do a 'not nested doc' query, but `whereNestedDoc` doesn't currently support passing an operator, and annoyingly it would mean a braking change to add the `$operator` var in the standard order in args. Adding a more generic `whereNot()` method like this offers the same functionality, and just wraps the given query in a `must_not` query.

feat: support `whereNot()`

---

src/QueryProcessor.php
src/Searchable.php

Let's say I have the following mapping:
```json
{
"mappings": {
"refund": {
"_parent": {
"type": "booking"
},
"properties": {
"amount": "double"
}
}
}
}
```
When I'm querying those documents, the returned model doesn't contain `_parent` because it's not within `_source`.
Here's an example of what's in the `$result` variable that's being passed into the `documentFromResult` method:
```php
[
"index" => "index_name",
"_type" => "refund",
"_id" => "12345",
"_score" => 1.0,
"_routing" => "abcdef",
"_parent" => "abcdef",
"_source" => [
"amount" => 100
]
]
```
This change allows model to be hydrated with the `_parent` ID if present in an attribute called `_parent`. It'll also unset this field before saving the model.

feat: add _parent to document

---

composer.json
composer.lock
src/Connection.php
src/Console/Mappings/IndexListCommand.php
src/QueryBuilder.php
src/QueryGrammar.php
src/QueryProcessor.php
src/Searchable.php

This package seems to be in development still, I've taken the liberty to add some change to make it compatible to laravel 8.
I've updated all the `str_` helpers to use the `Str` facade instead, and also update some of the internal syntaxes.
Im not so happy about the way I solved an issue with the column names, but it does work. The problem was that some external packages I was using use `tablename.column` when updating/selecting data, so I needed to remove that `tablename`.
Ive also added support for update directly on a query builder object.

Updated support to laravel 7+ and a bunch of other minor changes.

---

src/QueryGrammar.php

`$query->where('field', 'exists', false)` didn't flip the query to `must_not`.

fix: support for must not exist
